apiVersion: v1
kind: Service
metadata:
  name: ok
  namespace: example
  labels:
    app: ok
    component: api
spec:
  selector:
    app: ok
  ports:
    - name: http-port
      port: 80
      targetPort: ok-port